name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: 'gcp-low-traffic-runner'
  AR_REPO_LOCATION: 'us-central1'
  REPOSITORY_NAME: 'gcp-low-traffic-repo'
  AR_URL: 'us-central1-docker.pkg.dev/gcp-low-traffic-runner/gcp-low-traffic-repo'
  SERVICE_ACCOUNT: 'my-github-actions-service@gcp-low-traffic-runner.iam.gserviceaccount.com'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/702533190494/locations/global/workloadIdentityPools/github/providers/my-repo'
  IMAGE_NAME: 'portfolio-latest'
  SERVICE_NAME: 'portfolio-service'
  REGION: 'us-central1'

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          project_id: ${{ env.PROJECT_ID }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Authenticate Docker with Artifact Registry
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: ${{ env.AR_URL }}

      - name: Build and Push Container to Artifact Registry
        run: |
          docker build -t "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" -t "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:latest" .
          docker push "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          docker push "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:latest"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:latest \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated