name: Build and Push to Artifact Registry

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: gcp-low-traffic-runner # Replace with your GCP project ID
  AR_REPO_LOCATION: 'us-central1'
  REPOSITORY_NAME: gcp-low-traffic-repo # Artifact Registry repository name
  AR_URL: 'us-central1-docker.pkg.dev/gcp-low-traffic-runner/gcp-low-traffic-repo'
  SERVICE_ACCOUNT: 'my-github-actions-service@gcp-low-traffic-runner.iam.gserviceaccount.com'

permissions:
  id-token: write # Required for OIDC authentication
  contents: read # Required for actions/checkout

jobs:
  push_to_ar:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          project_id: ${{ env.PROJECT_ID }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.AR_REPO_LOCATION }}-docker.pkg.dev'

      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" ./
          docker push "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"